---
version: "3.7"

services:
    web:
        image: bearstech/nginx:1.14
        labels:
            traefik.enable: "true"
            traefik.backend: demo:multiplexer:web
            traefik.frontend.rule: Host:localhost
            sh.factory.project: demo

    traefik:
        image: traefik:1.7
        ports:
            - 80:80
            - 8080:8080
        command: -c /etc/traefik.cfg
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.cfg:/etc/traefik.cfg
            - ./log:/var/log

