---

input:
  file:
    path: log/access.log

filters:
  - docker:
      labels:
        - sh.factory.project

output:
  stdout:
  #file:
  #  path_pattern: ./traefik_${ sh.factory.project }.log
  fluent:
    tag: demultiplexer
    timezone: Europe/Paris
    labels:
        - sh.factory.project
  prometheus:
    label: sh.factory.project
    #salt: aiw2eizai1equoYohph3iy4OzuHee1Ne
    addr: 127.0.0.1:8084
